### ISSUE TITLE
Una carátula para el apunte de C.

### ISSUE THREAD

**Issue by santisis** [algoritmos-rw/algo2_apuntes#9]
El apunte de C son 47 páginas de material e, inicialmente al menos, se diseñó como el material "liviano" de los temas que había que cubrir durante el curso.

Jerárquicamente, dentro de los apuntes del lenguaje es el más relevante (los otros profundizan sobre un sólo tema particular o son filminas mucho más livianas y sintéticas).

Siendo que vendría a ser **el** apunte de C del curso, creo que debería tener una carátula, una nota de copyright, algo que especifique quiénes son los autores y que es un material original de nuestro curso. La realidad es que hoy uno abre el apunte y el PDF se ve absolutamente anónimo y sin una referencia al curso. Esa falta de contexto para mí hace que se le reste relevancia ante otros apuntes enlazados cuando se revisa el material.

La única nota de copyright que tiene el apunte actualmente es un comentario en el header del .tex.

**Comment by santisis** [comment]
> Está bien esto @santisis ? Es como está estructurado el apunte de algoritmos 1.
> 
> * Primera pág:
>   "Algoritmos y Programación II"
>   "Introducción al Lenguaje C (o simplemente 'el lenguaje C')"
> * Índice
> * Apunte en sí
> * Ultíma pagina de copyright (acá que va? creative commons?)

Sí, la licencia es CC, está la nota de copyright como comentario en el fuente LaTeX:

```tex
% Copyright (C) 2010-2013, Maximiliano Curia <maxy@gnuservers.com.ar>,
%               2010-2013, Margarita Manterola <marga@marga.com.ar>

% Esta obra está licenciada de forma dual, bajo las licencias Creative
% Commons:
%  * Atribución-Compartir Obras Derivadas Igual 2.5 Argentina
%    http://creativecommons.org/licenses/by-sa/2.5/ar/
%  * Atribución-Compartir Obras Derivadas Igual 3.0 Unported
%    http://creativecommons.org/licenses/by-sa/3.0/deed.es_AR.
%
% A su criterio, puede utilizar una u otra licencia, o las dos.
% Para ver una copia de las licencias, puede visitar los sitios
% mencionados, o enviar una carta a Creative Commons,
% 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
```

Sobre el esquema que proponés, está bien para mí. Lo único importante importante es que quede en claro que es un apunte de la cátedra. Y sí, siendo que del apunte inicial del lenguaje se agregaron tantos capítulos está bueno que haya una tabla de contenidos al comienzo.

**Comment by FdelMazo** [comment]
Lo que veo en el .tex es 

```
% Carat no esta.
%\include{carat}
```

y

```
%\include{apendice}
%\include{referenc}
%\include{copyright}
%\typeout{Bibliography}

%\addcontentsline{toc}{chapter}{Referencias}

%\bibliography{referenc}
%\bibliographystyle{alpha}
```

Sabés si esos archivos estan en algun lado?

**Comment by dato** [comment]
En el repo antiguo de Bitbucket no están, y en la _historia_ de ese repo tampoco.

Pienso que lo mejor sería enviarles un mail a @maxyz y @marga-debian a ver si saben dónde están los archivos faltantes del apunte de algo2 (_carat.tex_, _apendice.tex_, etc.).

O capaz con las menciones no haga falta mail. :-)

**Comment by santisis** [comment]
> En el repo antiguo de Bitbucket no están, y en la _historia_ de ese repo tampoco.

En realidad ese repo es un import del último estado del repositorio de SVN que estuvo en el LUGFI primero y en bettercodes.org después. Se perdió todo el historial en el interín.

De todos modos el `copyright.tex` puede tomarse del del Apunte de Python de BitBucket; lo mismo corre para la carátula.
